### PR TITLE
Fix Regression on converting CAN-FD packets with removing encapsulation

### PR DESCRIPTION
**Pull request by RayanMRABET**

### CODE REVIEW

**Comment by RayanMRABET** [comment]
Hi @kayoub5 ,

In the previous pull request [Andi-10609 : Correct CAN-FD error frame conversion #37](https://github.com/Technica-Engineering/Technica.Traces.Tecmp.Converter/pull/37), we reversed the check for CAN FD packets when checking for the existence of error frames. This introduced a regression issue because, in the case of CAN FD, the error masks need to be shifted to correctly detect if an error frame is present.

could you review please

**Review by kayoub5 — APPROVED** [review]

**Review by kayoub5 — CHANGES_REQUESTED** [review]
None of the tests failed after you changed the code

Meaning you are missing a unit test for this case

**Comment by RayanMRABET** [comment]
I added in the last commit 2 packets that cover a negative scenario for CAN FD conversion

**Comment by kayoub5** [comment]
The last two frames in `tests/results/can_error_frames.pcapng` were not converted correctly, missing payload data

**Comment by RayanMRABET** [comment]
> The last two frames in `tests/results/can_error_frames.pcapng` were not converted correctly, missing payload data

I’ve fixed this regression. Can you please review it?

**Comment by RayanMRABET** [comment]
> Frame 3 and 4 not converted correctly

issue fixed in last commit

**Comment by kayoub5** [comment]
@RayanMRABET the PR does fix the issue, but there is one case that was missed when it comes to error reporting

In TECMP, if the data flag "Acked" is 0 for a CAN frame, that's a CAN Error.

**Review by kayoub5 — APPROVED** [review]

**Pull request merged**
