### PR TITLE
make packet queue 1 when tecmp has tx flag

### PR DESCRIPTION
**Pull request by sensokame**
when tecmp packet has tx flag, make packet queue value 1

### CODE REVIEW

**Comment by sensokame** [comment]
@kayoub5 can you check this PR?

**Comment by kayoub5** [comment]
no pcap changes?

**Comment by sensokame** [comment]
there was no pcap that has TX : 1 in the test input

**Comment by kayoub5** [comment]
> there was no pcap that has TX : 1 in the test input

then how did you test it?

**Comment by sensokame** [comment]
I didn't 😣

**Comment by sensokame** [comment]
@kayoub5 
I added tests, also the current behaviour is
when there is a tx flag, epb_queue is set to 1.
inbound/outbound flag is only set when using mapping commmand

**Pull request merged**
